name: progrid
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  provider: ^6.1.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  path_provider: ^2.1.5
  http: ^1.2.2
  permission_handler: ^11.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  fl_chart: ^0.69.2
  flutter_map_marker_cluster: ^1.4.0
  image_watermark: ^0.1.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/